name: Snowflake Deploy

on:
  push:
    paths:
      - 'TABLE_ONE.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install SnowSQL
      run: # Add commands to install SnowSQL or other Snowflake clients

    - name: Run Snowflake Script
      run: snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -u ${{ secrets.SNOWFLAKE_USER }} -p ${{ secrets.SNOWFLAKE_PASS }} -d ${{ secrets.SNOWFLAKE_DB }} -f TABLE_ONE.sql
