name: Snowflake Deploy

on:
  push:
    paths:
      - 'TABLE_ONE.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install SnowSQL
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
        SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      

    - name: Run Snowflake Script
      run: ~/bin/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -u ${{ secrets.SNOWFLAKE_USER }} -p ${{ secrets.SNOWFLAKE_PASS }} -d ${{ secrets.SNOWFLAKE_DB }} -f TABLE_ONE.sql
